package com.example.caiyue.androidstuiodemo.model;

public class ArticleModel {
    private String agreeCount,
    agreeStates,
    authorHeadPath,
    authorName,
    cityCode,
    className,
    content,
    distributionChannel,
    documentClassSerial,
    forwardAmount,
    id,
    image,
    imageShowType,
    introduce,
    isAllowReview,
    isCollection,
    isHideReview,
    isRecommed,
    keyWord,
    noAgreeCount,
    openTime,
    readAmount,
    releaseDate,
    releaseOperator,
    releaseOperatorName,
    replyCount,
    source,
    status,
    thanksCount,
    thanksStates,
    tipsAgree,
    tipsStatus,
    title,
    type,
    typeName,
    updateTime,
    videoId,
    videoUrl;
}
